### ISSUE TITLE
Error: Unknown platforms: prod

### ISSUE THREAD

**Issue by RyanMcDonald** [jbrownssf/ionic-environment-flags#4]
Your solution works great for dev and non-platform-specific builds. But when I try to run `ionic build android --release --prod --env prod`, the build command assumes the trailing `prod` is a platform and we end up with `Error: Unknown platforms: prod`.

Also in the README, it says that `-env=p` can be used, but that is not the case anymore.

**Comment by jpbrown250** [comment]
Thank you, I'll take a look into this and see how it can be fixed.

**Comment by jpbrown250** [comment]
~~I believe that I have pin pointed the feature that is causing the conflict. It has to do with [cordova's build commands](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#cordova-build-command) allowing for anonymous platform specific tags. I'm looking to see if there is a way to circumvent this feature without removing it.~~

edit
Above is wrong, I was tracking the wrong problem. That issue was related to `reflect-metadata` and I ran `npm install reflect-metadata --save` and re-build npm with `npm rebuild`.

**Comment by jpbrown250** [comment]
@RyanMcDonald could you try running the command like this:

`ionic build android --release --prod -- --env prod`

and let me know what response you get?

**Comment by RyanMcDonald** [comment]
@jbrownssf That works! 😃

**Comment by jpbrown250** [comment]
Awesome, I'll update the repo with that fix and correct the -env=p. Thank you for taking the time to report the issue.
